theme = "gruvbox"

[editor]
line-number = "relative"
mouse = false
color-modes = true
bufferline = "always"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[editor.statusline]
left = ["mode", "spacer", "version-control", "spacer", "diagnostics", "file-name"]
right = ["position-percentage", "position", "spacer"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"