[theme]
name = "zenburn"

[helix]
inherits = "default_dark"

[palette]
bg = "#3f3f3f"
bg_alt = "#2b2b2b"
bg_dim = "#303030"
fg = "#dcdccc"
fg_dim = "#a6a39f"
cursor = "#ffffd7"
selection = "#4f4f4f"
accent = "#f0dfaf"
red = "#cc9393"
green = "#7f9f7f"
yellow = "#f0dfaf"
blue = "#6ca0a3"
magenta = "#dc8cc3"
cyan = "#8cd0d3"
orange = "#dfaf8f"

[ansi.normal]
black = "#4f4f4f"
red = "#cc9393"
green = "#7f9f7f"
yellow = "#f0dfaf"
blue = "#6ca0a3"
magenta = "#dc8cc3"
cyan = "#93e0e3"
white = "#dcdccc"

[ansi.bright]
black = "#5f5f5f"
red = "#dca3a3"
green = "#8fb28f"
yellow = "#f0dfaf"
blue = "#8cd0d3"
magenta = "#ec93d3"
cyan = "#93e0e3"
white = "#ffffd7"

[tmux]
status_bg = "bg"
status_fg = "fg"
status_inactive_fg = "fg_dim"
pane_border = "#4f4f4f"
pane_active_border = "green"
message_bg = "bg_alt"
message_fg = "fg"
clock = "green"
bell = "red"
