[editor]
scrolloff = 8
rulers = [80]
line-number = "relative"
cursorline = true
bufferline = "always"
true-color = true
mouse = false
color-modes = true
auto-format = true

[editor.indent-guides]
render = true
character = "â”‚"

[editor.whitespace]
render = { trailing = true }

[editor.statusline]
left = ["mode", "spacer", "version-control", "spacer", "diagnostics", "file-name"]
right = ["position-percentage", "spacer", "position", "spacer", "file-encoding"]
mode.normal = "N"
mode.insert = "I"
mode.select = "S"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
display-inlay-hints = true
auto-signature-help = true
display-signature-help-docs = true

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "hint"
