[keys.normal]
"esc" = ["normal_mode", ":format", ":write"]
"#" = "toggle_comments"
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"

[keys.normal.space]
q = ":bc"
o = "file_picker_in_current_buffer_directory"

[keys.normal.space.w]
r = ":rla"
